runtime : nodejs14
env : standard

env_variables:
      SQL_USER : root
      SQL_PASSWORD : mysql
      SQL_DATABASE : noteapp
      INSTANCE_CONNECTION_NAME : noteapp-318213:us-east1:mysql



# beta_setting :
#        cloud_sql_instance :  notetakingapp-317909:us-central1:mysql        